//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorioProg3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cotizacion
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string tipoMoneda { get; set; }
        public double valor { get; set; }
    }
}
