//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorioProg3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using obligatorioProg3.CustomValidations;

    public partial class horario_programa
    {
        public int idPrograma { get; set; }
        public string dia { get; set; }

        [ValidacionHorariosPrograma]
        public System.TimeSpan horaInicio { get; set; }

        [ValidacionHorariosPrograma]
        public System.TimeSpan horaFinal { get; set; }
    

        public virtual programa programa { get; set; }
    }
}
