//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorioProg3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vozDelEsteBsdEntities : DbContext
    {
        public vozDelEsteBsdEntities()
            : base("name=vozDelEsteBsdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> cliente { get; set; }
        public virtual DbSet<clima> clima { get; set; }
        public virtual DbSet<comentario> comentario { get; set; }
        public virtual DbSet<conductor> conductor { get; set; }
        public virtual DbSet<cotizacion> cotizacion { get; set; }
        public virtual DbSet<datosCliente_dependenciaCedula> datosCliente_dependenciaCedula { get; set; }
        public virtual DbSet<horario_programa> horario_programa { get; set; }
        public virtual DbSet<invitado> invitado { get; set; }
        public virtual DbSet<noticia> noticia { get; set; }
        public virtual DbSet<patrocinador> patrocinador { get; set; }
        public virtual DbSet<permiso> permiso { get; set; }
        public virtual DbSet<programa> programa { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
