//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace obligatorioProg3
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticia
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string contenido { get; set; }
        public System.DateTime fechaPublicacion { get; set; }
        public string imagen { get; set; }
    }
}
